### ISSUE TITLE
Potential flaw in acking messages

### ISSUE THREAD

**Issue by Scooletz** [Particular/NServiceBus.AzureStorageQueues#148]
Performance tests sometimes report a message that can't be acked because of deletion.
It needs to be investigated and discussed.

```
 2016-08-29 13:35:09.8906|INFO|17|NServiceBus.RecoverabilityExecutor|Immediate Retry is going to retry message '3bd0ff53-5f0b-4911-854b-a6710100ce0c' because of an exception:
Microsoft.WindowsAzure.Storage.StorageException: The remote server returned an error: (404) Not Found. ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
   at Microsoft.WindowsAzure.Storage.Shared.Protocol.HttpResponseParsers.ProcessExpectedStatusCodeNoException[T](HttpStatusCode expectedStatusCode, HttpStatusCode actualStatusCode, T retVal, StorageCommandBase`1 cmd, Exception ex)
   at Microsoft.WindowsAzure.Storage.Queue.CloudQueue.<DeleteMessageImpl>b__3a(RESTCommand`1 cmd, HttpWebResponse resp, Exception ex, OperationContext ctx)
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndGetResponse[T](IAsyncResult getResponseResult)
   --- End of inner exception stack trace ---
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndExecuteAsync[T](IAsyncResult result)
   at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions.<>c__DisplayClass4.<CreateCallbackVoid>b__3(IAsyncResult ar)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.AzureStorageQueues.AtLeastOnceReceiveStrategy.<Receive>d__1.MoveNext()
Request Information
RequestID:f9883550-0003-0090-6bfa-01889e000000
RequestDate:Mon, 29 Aug 2016 13:35:43 GMT
StatusMessage:The specified message does not exist.
ErrorCode:MessageNotFound
```

**Comment by Scooletz** [comment]
I've tried the following approach to reproduce. I didn't succeed in ~20 runs. Let me describe the repro scenario:

1. Use top master of [EndToEnd](https://github.com/Particular/EndToEnd) - clean clone on my machine.
1. Run following scenario `GatedSendLocalRunner(V6~AzureStorageQueues~)`
1. Observing `ASQ` (output console) for failing on `Ack` operations (like in the description of the issue).

@ramonsmits please chime in to validate the scenario we observed. Is it possible that the test you run was performed with old binaries? Could you get a clean clone and rerun it?

It would be beneficial if at least one more @Particular/azure-storage-queues-maintainers could run this on their machine.

**Comment by SeanFeldman** [comment]
Tried is locally. Nothing on this end. Test passes and nothing is thrown on the screen. Where's the log file (in case it's written and passes too fast)?

**Comment by danielmarbach** [comment]
I made today a dozen runs with 1000 msgs, 5000 msg and 10000 msgs prefilled into the queue and receive it with multiple concurrency level (standard, 16,32, 64 and 100). couldn't reproduce it. The transport is also looking very good on the performance profiling and memory profiling. Well done all!

**Comment by Scooletz** [comment]
I'm closing it then. /cc @ramonsmits

**Comment by ramonsmits** [comment]
I can't reproduce it anymore. Could the cause be due message with an expired TTL that are deleted by ASQ?

Seems the stack trace is indicating that the message is already deleted 

    Microsoft.WindowsAzure.Storage.Queue.CloudQueue.<DeleteMessageImpl

I would say that should be handled gracefully. If this happens we could log an INFO event stating that the message is already deleted from the queue.

**Comment by Scooletz** [comment]
That would mean @ramonsmits that a message expired between getting it from a queue and deleting it which is highly unlikely. Again, the very same error you could get when running ScaleOut before the fix.
