### ISSUE TITLE
TaskCanceledException during graceful shutdown of endpoint

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.AzureStorageQueues#242]
Gracefully shutting down an endpoint can result in the following warning to be logged which should not happen during a graceful shutdown.

```
2017-07-21 16:26:22.196 WARN  NServiceBus.Azure.Transports.WindowsAzureStorageQueues.DelayDelivery.DelayedMessagesPoller Failed at spinning the poller
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NServiceBus.Azure.Transports.WindowsAzureStorageQueues.DelayDelivery.DelayedMessagesPoller.<SpinOnce>d__20.MoveNext() in C:\BuildAgent\work\4e5353dd260f0a07\src\Transport\DelayDelivery\DelayedMessagesPoller.cs:line 197
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Azure.Transports.WindowsAzureStorageQueues.DelayDelivery.DelayedMessagesPoller.<InnerPoll>d__17.MoveNext() in C:\BuildAgent\work\4e5353dd260f0a07\src\Transport\DelayDelivery\DelayedMessagesPoller.cs:line 101
```

**Comment by Scooletz** [comment]
Which version is it @ramonsmits ?

**Comment by ramonsmits** [comment]
@Scooletz added package info to description

**Comment by danielmarbach** [comment]
@ramonsmits while the warning is inconvenient I agree we see no reason to patch this in 7.4.x. Instead we sent in a PR that fixes it for the next major version https://github.com/Particular/NServiceBus.AzureStorageQueues/pull/289
