### ISSUE TITLE
Exception when creating SendOnly endpoint (8.0.0-beta0005)

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.AzureStorageQueues#287]
When starting a SendOnly endpoint you will get the following exception:

```
System.InvalidOperationException: Receive transaction mode isn't available since this endpoint is configured to run in send-only mode.
   at NServiceBus.ConsistencyGuarantees.TransactionModeSettingsExtensions.GetRequiredTransactionModeForReceives(ReadOnlySettings settings)
   at NServiceBus.Azure.Transports.WindowsAzureStorageQueues.DelayDelivery.DelayedMessagesPoller.Init(ReadOnlySettings settings)
   at NServiceBus.Azure.Transports.WindowsAzureStorageQueues.DelayDelivery.DelayedMessagesPoller.Start(ReadOnlySettings settings, CancellationToken cancellationToken)
   at NServiceBus.AzureStorageQueues.AzureStorageQueueInfrastructure.Start()`
```

**Comment by SeanFeldman** [comment]
What endpoint's configuration code looks like?

**Comment by danielmarbach** [comment]
@ramonsmits potential fix applied https://github.com/Particular/NServiceBus.AzureStorageQueues/pull/288
