### ISSUE TITLE
DelayedMessagesPoller|Failed at spinning the poller :TaskCanceledException: A task was canceled.

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.AzureStorageQueues#291]
During shutdown, the following exception occured a few times. It seems some logic doesn't react correctly to shutdown.

```
2017-11-21 03:58:10,229|WARN|89|NServiceBus.Azure.Transports.WindowsAzureStorageQueues.DelayDelivery.DelayedMessagesPoller|Failed at spinning the poller
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Azure.Transports.WindowsAzureStorageQueues.DelayDelivery.DelayedMessagesPoller.<SpinOnce>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Azure.Transports.WindowsAzureStorageQueues.DelayDelivery.DelayedMessagesPoller.<InnerPoll>d__16.MoveNext()
```

**Comment by SeanFeldman** [comment]
@ramonsmits to confirm, this is version 8 of the transport?

**Comment by ramonsmits** [comment]
@SeanFeldman I'm not sure it also seems to be a duplicate of https://github.com/Particular/NServiceBus.AzureStorageQueues/issues/242 so closing this as I don't have those test results anymore.
