### ISSUE TITLE
Core 6: Error at shutdown WARN  NServiceBus.Azure.Transports.WindowsAzureStorageQueues.DelayDelivery.DelayedMessagesPoller Failed at spinning the poller

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.AzureStorageQueues#318]
I sometimes get the following error during endpoint shutdown which I think should should be gracefully handled.

```
2018-01-29 09:20:51.804 WARN  NServiceBus.Azure.Transports.WindowsAzureStorageQueues.DelayDelivery.DelayedMessagesPoller Failed at spinning the poller
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NServiceBus.Azure.Transports.WindowsAzureStorageQueues.DelayDelivery.DelayedMessagesPoller.<SpinOnce>d__20.MoveNext() in C:\BuildAgent\work\956312761da410d2\src\Transport\DelayDelivery\DelayedMessagesPoller.cs:line 197
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Azure.Transports.WindowsAzureStorageQueues.DelayDelivery.DelayedMessagesPoller.<InnerPoll>d__17.MoveNext() in C:\BuildAgent\work\956312761da410d2\src\Transport\DelayDelivery\DelayedMessagesPoller.cs:line 101
```

**Comment by danielmarbach** [comment]
Potential fix https://github.com/Particular/NServiceBus.AzureStorageQueues/pull/319

**Comment by SeanFeldman** [comment]
Closed via https://github.com/Particular/NServiceBus.AzureStorageQueues/commit/2a54bbe401d75875a95d0481d777853814de381c

**Comment by ramonsmits** [comment]
@SeanFeldman As this issue was specific to core v6 so ASQ v7 does this mean this is a no fix for core 6 as that commit seems to be part of v8?

**Comment by ramonsmits** [comment]
Seems I already reported this issue earlier for v7 and that seems to contain a decision to not fix it for the currently released major version:

-  https://github.com/Particular/NServiceBus.AzureStorageQueues/issues/242#issuecomment-342469520

> while the warning is inconvenient I agree we see no reason to patch this in 7.4.x. Instead, we sent in a PR that fixes it for the next major version
