### ISSUE TITLE
Incoming messages failing unwrapping are processed infinitely, filling up the error queue.

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureStorageQueues#405]
### Symptoms

Incoming messages failing unwrapping are processed infinitely, filling up the error queue. The original incoming messages are not removed from the input queue and the following warning is logged:

```
WARN : Azure Storage Queue transport failed pushing a message through pipeline
Type: Microsoft.WindowsAzure.Storage.StorageException
Message: The remote server returned an error: (404) Not Found.
Source: Microsoft.WindowsAzure.Storage
StackTrace:
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndExecuteAsync[T](IAsyncResult result) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 50
   at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions.<>c__DisplayClass7.<CreateCallbackVoid>b__5(IAsyncResult ar) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Util\AsyncExtensions.cs:line 121
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.AzureStorageQueues.MessageRetrieved.<Unwrap>d__3.MoveNext() in C:\BuildAgent\work\3c19e2a032c05076\src\Transport\MessageRetrieved.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.AzureStorageQueues.MessagePump.<InnerReceive>d__7.MoveNext() in C:\BuildAgent\work\3c19e2a032c05076\src\Transport\MessagePump.cs:line 153
TargetSite: T EndExecuteAsync[T](System.IAsyncResult)
```

### Who's affected

Customers using Azure Storage Queue transport with a [custom envelope unwrapper](https://docs.particular.net/transports/azure-storage-queues/configuration#custom-envelope-unwrapper).

### Root cause

When a message arrives, it's handled as a `MessageRetrieved`.  The first step before a message can be processed is to unwrap it. If the message is poisonous or a custom unwrapper is failing, the message is supposed to be moved to the error queue. Instead, the message will remain in the main queue, will cause infinite processing, spamming error queue with infinite copies of the message.

The root cause of the issue is the implementation of the `MessageRetrieved.Unrawp()` method that is sending the originally retrieve message to the error queue and complete it using the same object. The Storage Queue API when sending a message updated message ID and its pop receipt. Therefore the original message's information is lost and it cannot be completed. From the [documentation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.queue.cloudqueue.addmessageasync?view=azure-dotnet-legacy#Microsoft_Azure_Storage_Queue_CloudQueue_AddMessageAsync_Microsoft_Azure_Storage_Queue_CloudQueueMessage_):

> The CloudQueueMessage message passed in will be populated with the pop receipt, message ID, and the insertion/expiration time.

Originally reported on [StackOverflow](https://stackoverflow.com/questions/61329547/nservicebus-with-azurestoragequeues-not-removing-poison-messages-from-input-queu).

**Comment by SeanFeldman** [comment]
We have prioritized this issue near the top of our list and will be working on it as soon as we can.

**Comment by Beau-Marwaha-Wegmans** [comment]
Hello, is there any timeline available for when this fix will be available through NuGet?

**Comment by danielmarbach** [comment]
We have released the updated versions to nuget. More information available at https://discuss.particular.net/t/nservicebus-azure-transports-windowsazurestoragequeues-7-5-8-8-1-5-and-8-2-1-patch-releases-available/1781
