### ISSUE TITLE
Using `UseQueueServiceClient` instead of a connection string to configure the transport results in an exception when the endpoint starts

### ISSUE THREAD

**Issue by seanfarmar** [Particular/NServiceBus.AzureStorageQueues#664]
As per documentation: https://docs.particular.net/transports/azure-storage-queues/configuration?#configuration-api

We shuld be able to call `UseQueueServiceClient()` however, when I build and run this I get an exception about a null connection string
```
"Value cannot be null. (Parameter 'connectionString')"

   at NServiceBus.Guard.AgainstNullAndEmpty(String argumentName, String value) in /_/src/Transport/Guard.cs:line 23
   at NServiceBus.AzureStorageQueueTransport.Initialize(SettingsHolder settings, String connectionString) in /_/src/Transport/AzureStorageQueueTransport.cs:line 32
   at NServiceBus.TransportSeam.Create(Settings transportSettings, Configuration hostingConfiguration) in /_/src/NServiceBus.Core/Transports/TransportSeam.cs:line 20
   at NServiceBus.EndpointCreator.Initialize() in /_/src/NServiceBus.Core/EndpointCreator.cs:line 44
   at NServiceBus.EndpointCreator.Create(SettingsHolder settings, Configuration hostingConfiguration) in /_/src/NServiceBus.Core/EndpointCreator.cs:line 27
   at NServiceBus.HostCreator.<CreateWithInternallyManagedContainer>d__1.MoveNext() in /_/src/NServiceBus.Core/Hosting/HostCreator.cs:line 86
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at NServiceBus.Endpoint.<Start>d__1.MoveNext() in /_/src/NServiceBus.Core/Endpoint.cs:line 29
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Program.<Main>d__0.MoveNext() in C:\Users\sean.farmar\OneDrive\Desktop\stuff\Redactus\AzureStorageQueueListener\storage-queues_asqn_10_net5_0\Endpoint1\Program.cs:line 47
```

I have been able to reproduce this using the basic sample and chenging the code to use a QueueServiceClient and shown below:

```
        var transport = endpointConfiguration.UseTransport<AzureStorageQueueTransport>();
        transport.DisablePublishing(); 
        transport.DelayedDelivery().DisableDelayedDelivery();
        transport.DelayedDelivery().DisableTimeoutManager();

        Uri uri = new Uri("CLIENT-SAS-TOKEN");
        QueueServiceClient serviceClient = new QueueServiceClient(uri);

        transport.UseQueueServiceClient(serviceClient);
        
```

**Comment by kentdr** [comment]
Hi Sean. We have prioritized your issue near the top of our list and will be working on it as soon as we can.  Thank you for the steps to reproduce.

**Comment by mikeminutillo** [comment]
@seanfarmar We are working on a fix for this that should be released as a part of 10.0.3 (and backported to 9.0.4)

With this version it will be possible to disable delayed delivery and not configure a blob service client.

At the moment, there is not a public API to disable the native pub-sub that relies on the cloud table client provider. The `transport.DisablePublishing()` API only disables message-driven pub-sub compatibility. It has an unfortunately confusing name, which we'll be taking a look at.

Out of interest, why are you trying to turn off these features?

**Comment by seanfarmar** [comment]
@mikeminutillo actually I was just experimenting to get the client working, the customer should be ok without disabling these features...

**Comment by SzymonPobiega** [comment]
@seanfarmar the package is on NuGet:)
